name: generate pacman animation

on:
  schedule:
    - cron: "0 0 * * *"  # ejecuta una vez al día
  workflow_dispatch:      # permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Pac-Man animation
        uses: Platane/snk@v3
        with:
          github_user_name: jornu99
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist  # Carpeta local donde se generarán SVG y GIF

      - name: Push SVG/GIF to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
