name: generate pacman animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Pac-Man animation
        uses: anuraghazra/github-contribution-grid-snake@pacman
        with:
          github_user_name: jornu99
          color_snake: "#F9E14B"
          color_dots: "#333333"
          color_ghost: "#00FFFF"

      - name: Push SVG
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
